# Generated by Django 4.0.4 on 2022-10-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_shop_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category', upload_to='category_images'),
            preserve_default=False,
        ),
    ]
