# Generated by Django 4.0.4 on 2022-10-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='brand_images')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='top_product',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='trending_product',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
