# Generated by Django 4.0.4 on 2022-10-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='suite a', max_length=500),
            preserve_default=False,
        ),
    ]
