# Generated by Django 4.0.4 on 2022-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_stock',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
