# Generated by Django 4.0.4 on 2022-11-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_in_stock_alter_order_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='in_stock',
        ),
    ]
