# Generated by Django 4.0.4 on 2022-11-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_order_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
