# Generated by Django 4.0.4 on 2022-11-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_myuser_country_myuser_postcode_myuser_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
