# Generated by Django 4.0.4 on 2022-11-23 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_myuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='Payment status'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
